### PR TITLE
Add C++ inference example and code

### PR DESCRIPTION
**Pull request by ZDisket**
This is complete C++ code (from text processing to saving audio) for inference with TensorflowTTS/FastSpeech2 (phonetic MFA-aligned from my fork) and Multi-Band MelGAN using the Tensorflow C API. Can compile and run for Windows 64-bit out of the box(solution and project), but the code is cross-platform assuming one provides the required libraries. The project builds a simple command line program where one inputs sentences and they are generated and saved as WAVs.

There's a link for compiled binaries, libraries, and a sample model required to compile for Win64 in the README.

It will allow deploying TensorflowTTS models in a portable way into desktop environments.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@candlewill @machineko @azraelkuan can you guys take a look :))).

**Comment by dathudeptrai** [comment]
@ZDisket can we run it on ubuntu ? :))

**Comment by ZDisket** [comment]
@dathudeptrai Out of the box, you can try WINE, it works for simple console apps in my experience. Since the program has no platform dependent code, to compile, you just need libs and includes for Linux versions of Phonetisaurus, OpenFST and Tensorflow C API (that one can be downloaded, the rest you'll have to compile from source).

**Comment by azraelkuan** [comment]
> @candlewill @machineko @azraelkuan can you guys take a look :))).
have no experience about this

**Comment by machineko** [comment]
> @dathudeptrai Out of the box, you can try WINE, it works for simple console apps in my experience. Since the program has no platform dependent code, to compile, you just need libs and includes for Linux versions of Phonetisaurus, OpenFST and Tensorflow C API (that one can be downloaded, the rest you'll have to compile from source).

Can you add it in readme or scripted some bash to download dependencies based on platform?

**Comment by ZDisket** [comment]
@machineko I'll add to the README what has to be downloaded. The users will have to compile those from source.

**Comment by ZDisket** [comment]
@machineko @dathudeptrai Look good? Any success running the demo in Ubuntu with WINE? Also, do any of these people that were requested know C++?

**Comment by machineko** [comment]
@dathudeptrai Didnt have time yet to compile everything (im on arch not ubuntu but still shouldnt be a problem) after weekend I will try it :P

**Comment by dathudeptrai** [comment]
> Also, do any of these people that were requested know C++?

@candlewill is a master in C++ :)), also in TTS. @azraelkuan not sure. @machineko not sure :)). About me: almost zero =))))))))))))))))))))

**Comment by machineko** [comment]
I have almost zero exp in c++ but a lot in pure C mostly for optimization :P

File: examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj.filters [hunk 1]
```diff
@@ -0,0 +1,87 @@
+﻿<?xml version="1.0" encoding="utf-8"?>
```
[the remark this answers is not in the document]
Comment (ZDisket) [reply examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj.filters:1]: That's Visual Studio config file, which is required for the Visual Studio solution and project files so people with Windows and Visual Studio can load it up and compile.

File: examples/cppwin/TensorflowTTSCppInference/Voice.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
+#include "Voice.h"
+#include "ext/ZCharScanner.h"
+const std::vector<std::string> Phonemes = { "AA","AA0","AA1","AA2","AE","AE0","AE1","AE2","AH","AH0","AH1","AH2","AO","AO0","AO1",
```
[the remark this answers is not in the document]
Comment (ZDisket) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: I also considered that before deciding against it; this is just an example and if someone wants to adapt it to their dataset then they should take it then change it. It's not designed to be a one size fits all solution, but something that people can use as a base for their project.

[the remark this answers is not in the document]
Comment (dathudeptrai) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: yeah :)) it's just example :D, we do not need make it general :D.

[the remark this answers is not in the document]
Comment (machineko) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: Maybe but every other example right now can be used in very easy way just changing few things in scripting part 
I think we should move in this direction. (In future prepro there will be mapper saving so you can load phonemes and other mappers from json files just like configs right now :P)

Still im not following any C++ standards so this is a question for  @candlewill

[the remark this answers is not in the document]
Comment (dathudeptrai) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: :))) for this case, i just to make sure it can be run then i will approve merge =)))))))))))))))).

File: examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj.filters (hunk 1 above)
[the remark this answers is not in the document]
Comment (machineko) [reply examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj.filters:1]: You can mark this as resolve :P

File: examples/cppwin/TensorflowTTSCppInference/Voice.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ZDisket) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: >In future prepro there will be saving all needed mappers so you can load phonemes and other mappers from json files just like configs right now

Why not leave it like this right now then later when those preprocessing steps are implemented I make it so that the program can load exported dictionaries? Because another issue is to agree on a format for storing the characters and IDs.

[the remark this answers is not in the document]
Comment (machineko) [reply examples/cppwin/TensorflowTTSCppInference/Voice.cpp:3]: We can just wait for @candlewill to check it and whole pr :P

**Comment by machineko** [comment]
Also did u do some benchmarks it is faster than python based version :D?

**Comment by ZDisket** [comment]
@machineko For a rough estimate of performance, see https://github.com/TensorSpeech/TensorFlowTTS/issues/179#issuecomment-670295696 . I never ran the Python version in my local PC, so I can't compare.

**Comment by machineko** [comment]
I'll compare later in next week on i9-9900k :P

**Comment by ZDisket** [comment]
@candlewill The only experience developing on Linux that I have is with Qt Creator, I can make a Qt project for compiling on Ubuntu 18.04.

**Comment by candlewill** [comment]
@ZDisket Well, I would base on your code to support CMake compilation.

**Comment by candlewill** [comment]
Update my progress:

I used `cmake-converter` tool to convert the vs project into a cmake project:

``` bash
cmake-converter -s TensorflowTTSCppInference.sln --verbose-mode --private-include-directories --warning-level=3
```

The converter tool has no handler to process the `<IncludePath>` and ` <LibraryPath>` node. We can manually create a new file `CMake/GlobalSettingsInclude.cmake` with content: 
```include_directories(${PROJECT_SOURCE_DIR}/deps/include)```
to fix the problem.

Then, I tried to compile it: 

```
cmake -S . -B build
# Launch compilation
cmake --build build
```

Then some compilation error occurred:

image

Maybe one reason is my gcc version (7.5.0) is too new to compile it.

**Comment by ZDisket** [comment]
@candlewill Give me your CMake files and I'll finish it.

**Comment by ZDisket** [comment]
@machineko You got it to compile on Linux?

**Comment by machineko** [comment]
Not yet ill try tommorow just accepted pr so i wont be blocking it

**Comment by candlewill** [comment]
Here is the cmakefilelists.zip. The zip file should be uncompressed to the `examples/cppwin` folder.

[cmakelists.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5060255/cmakelists.zip)

**Comment by machineko** [comment]
I also can't compile on gcc 7.5 on arch will upgrade gcc later

**Comment by ZDisket** [comment]
There's now Linux support, a precompiled demo can be downloaded (tested in Kubuntu 18.04) [here](https://drive.google.com/file/d/17wAVsxRpaPogPpzOiEJB8QJjF_wI60q2/view?usp=sharing).
Peek 2020-08-12 18-06

**Comment by machineko** [comment]
It's working for me on 7.5 gcc, on 9.3 I got *** stack smashing detected ***: <unknown> terminated
Aborted.
I'll benchmark it later

**Comment by dathudeptrai** [comment]
@ZDisket @machineko it run so fast in my laptop CPU.

**Comment by ZDisket** [comment]
@dathudeptrai So, you like it?

**Comment by dathudeptrai** [comment]
> @dathudeptrai So, you like it?

:))) the question is so serious :))). Just wait @candlewill review again :v

**Comment by ZDisket** [comment]
@dathudeptrai Don't worry, I was just surprised it was running fast, not in a hurry right now especially since I'm busy with [TensorVox](https://github.com/ZDisket/TensorVox).

**Comment by machineko** [comment]
It works fine on ubuntu but I still can't compile it on arch (i've tried gcc 7.5, 8, 10.3 and diff versions of dependencies dunno if its cause of https://github.com/FloopCZ/tensorflow_cc but i won't be trying any more right now :P).
Also can u compile second version as CLI or some rest API to test it?

**Comment by orikama** [comment]
Since I was getting this error: "was created with an older compiler than other objects; rebuild old objects and libraries" for Phonetisaurus and OpenFST libs while building this project in Visual Studio 2019, I wrote normal, not auto generated CMake, that builds Phonetisaurus, OpenFST and this project from source. Also tested it on Manjaro(arch) with gcc 10.
And changed Phonetisaurus sources a little to fix linker errors, because I couldn't find gcc analog for `/FORCE` :)

**Comment by orikama** [comment]
[CMakeLists.txt](https://github.com/TensorSpeech/TensorFlowTTS/files/5078948/CMakeLists.txt)
[Phonetisaurus.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5078949/Phonetisaurus.zip)

**Comment by ZDisket** [comment]
@orikama My fork of [Phonetisaurus ](https://github.com/ZDisket/Phonetisaurus)that I made for Linux compiling already has the required change to not require /FORCE; soon I'll make that one Windows compatible too.
And while I appreciate those CMake lists you made, I won't add them here because I can't maintain them. This C++ implementation will be updated in the future.

**Comment by orikama** [comment]
@ZDisket why you just can't get me to help? Plus, you depend on QT in Phonetisaurus which is unnecessary.
And what will be you solution to people who might want to compile this in VS 2019 ?

**Comment by ZDisket** [comment]
@orikama 
> And what will be you solution to people who might want to compile this in VS 2019 ?

Tell them to compile Phonetisaurus and OpenFST from source in VS2019. I provide prebuilt for VS2017 for convenience, but there's nothing stopping them from compiling it themselves. I'll update my Phonetisaurus fork to support Windows in a bit.

>Plus, you depend on QT in Phonetisaurus which is unnecessary.

Good point, I'll modify the README to use qmake.

>why you just can't get me to help? 

I assumed your contribution was just a one-time thing only. Let me think about it.

**Comment by orikama** [comment]
@ZDisket btw AudioFile.hpp also gave me error, when I was trying to build it on manjaro with gcc 10.
I tried `make CXXFLAGS="-fpermissive"`, but it didn't worked for me. I'm not familiar with gcc and make, so may be I did it wrong.
So I changed AudioFile also to make it work.

**Comment by ZDisket** [comment]
@orikama Weird that` -fpermissive` didn't work, but it did for me.

>I was lazy to figure out how to build Phonetisaurus with 'make' on windows, so I almost gave up :) Especially since you don't need to build it all and only need to include a couple files from it.

That's why I'm providing my fork to allow people to compile it, because this doesn't use Phonetisaurus but rather _libPhonetisaurus_, my modification with all the executables gone and only libraries.

**Comment by orikama** [comment]
If I'm not mistaken you still use more files from Phonetisaurus than you need to. You should check what files I left in my Phonetisaurus.zip

**Comment by ZDisket** [comment]
@orikama Interesting, I'll check it out.

**Comment by dathudeptrai** [comment]
@ZDisket Finish ?

**Comment by ZDisket** [comment]
@dathudeptrai Should be, I don't have anything else to do except clean up the libPhonetisaurus repo, but of course that's somewhere else.

**Review by dathudeptrai — APPROVED** [review]
